tables:
    xoopartners:
        options: {  }
        columns:
            xoopartners_id:
                name: xoopartners_id
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            xoopartners_category:
                name: xoopartners_category
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_uid:
                name: xoopartners_uid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_title:
                name: xoopartners_title
                type: string
                default: null
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_description:
                name: xoopartners_description
                type: text
                default: null
                notnull: true
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_image:
                name: xoopartners_image
                type: text
                default: null
                notnull: true
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_url:
                name: xoopartners_url
                type: string
                default: null
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_order:
                name: xoopartners_order
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_online:
                name: xoopartners_online
                type: boolean
                default: '1'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_visit:
                name: xoopartners_visit
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_hits:
                name: xoopartners_hits
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_accepted:
                name: xoopartners_accepted
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rates:
                name: xoopartners_rates
                type: float
                default: '0.00'
                notnull: true
                length: null
                precision: 5
                scale: 2
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_like:
                name: xoopartners_like
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_dislike:
                name: xoopartners_dislike
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_comments:
                name: xoopartners_comments
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_published:
                name: xoopartners_published
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [xoopartners_id]
                unique: true
                primary: true
    xoopartners_categories:
        options: {  }
        columns:
            xoopartners_category_id:
                name: xoopartners_category_id
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            xoopartners_category_parent_id:
                name: xoopartners_category_parent_id
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_category_title:
                name: xoopartners_category_title
                type: string
                default: null
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_category_description:
                name: xoopartners_category_description
                type: text
                default: null
                notnull: true
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_category_image:
                name: xoopartners_category_image
                type: string
                default: '0'
                notnull: true
                length: 100
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_category_order:
                name: xoopartners_category_order
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_category_online:
                name: xoopartners_category_online
                type: boolean
                default: '1'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_category_partners:
                name: xoopartners_category_partners
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [xoopartners_category_id]
                unique: true
                primary: true
    xoopartners_rld:
        options: {  }
        columns:
            xoopartners_rld_id:
                name: xoopartners_rld_id
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: true
                columnDefinition: null
                comment: null
            xoopartners_rld_partner:
                name: xoopartners_rld_partner
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rld_uid:
                name: xoopartners_rld_uid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rld_time:
                name: xoopartners_rld_time
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rld_ip:
                name: xoopartners_rld_ip
                type: text
                default: null
                notnull: true
                length: 16777215
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8_general_ci
            xoopartners_rld_rates:
                name: xoopartners_rld_rates
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rld_like:
                name: xoopartners_rld_like
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
            xoopartners_rld_dislike:
                name: xoopartners_rld_dislike
                type: boolean
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [xoopartners_rld_id]
                unique: true
                primary: true
